language: c

compiler: 
- gcc
- clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "OETxFX/UnIP+WlVTtHbDhdSFXzNg1Lv3IxYiPHGcu6fWj573P7hV5LRoBkdH14dveg1vISN8ufq4B6kG+7olpjh2AkSX0fUX7KFHgNhzJBFyaYym3ZXNxtF/uoD+gKyl5nXUy5dDBvaYtVKVwYQ3INp3fQ1aRjQ6IcVWzQUuRnA="

before_install:
 - uname -a
 - export DEBIAN_FRONTEND=noninteractive
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
 - sudo apt-get update -qq
 - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install -qq dbus libdbus-1-3 libdbus-1-dev

script: 
 - make clean
 - make
 - ls -la
 - sudo make install
 - ls /dev/input/*
 - ls -la /dev/input/by-path/
 - sudo ./test_ci_kbd_backlight_ctrl.sh
 - sudo make uninstall

addons:
  coverity_scan:
    project:
      name: "ruben2020/kbd_backlight_ctrl"
      description: "Keyboard Backlight Control Service"
    notification_email: ruben2020-git@users.sourceforge.net
    build_command_prepend: "make clean"
    build_command: "make"
    branch_pattern: coverity_scan

notifications:
  email:
    - ruben2020-git@users.sourceforge.net
  on_success: change
  on_failure: always

