language: c

compiler: 
- gcc
- clang

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "DhZECb-Y6leeWhDeFSKqkg"

before_install:
 - uname -a
 - export DEBIAN_FRONTEND=noninteractive
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
 - sudo apt-get update -qq
 - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install -qq dbus libdbus-1-3 libdbus-1-dev

script: 
 - make clean
 - make
 - ls -la
 - sudo make install
 - export DBUS_SESSION_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
 - export KBD_BACKLIGHT_CTRL_TIMEOUT=10
 - export KBD_BACKLIGHT_CTRL_INDEVICE=/dev/input/event4
 - timeout 20s kbd_backlight_ctrl
 - sudo make uninstall

addons:
  coverity_scan:

    project:
      name: ruben2020/kbd_backlight_ctrl
      version: 0.1
      description: Keyboard Backlight Control Service

    notification_email: ruben2020-git@users.sourceforge.net

    build_command_prepend:
     - uname -a
     - export DEBIAN_FRONTEND=noninteractive
     - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
     - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
     - sudo apt-get update -qq
     - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install -qq dbus libdbus-1-3 libdbus-1-dev

    build_command:
     - make clean
     - make

    branch_pattern: coverity_scan

notifications:
  email:
    - ruben2020-git@users.sourceforge.net
  on_success: change
  on_failure: always

