language: c

compiler: 
- gcc
- clang

before_install:
 - uname -a
 - export DEBIAN_FRONTEND=noninteractive
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
 - sudo apt-get update -qq
 - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install -qq dbus libdbus-1-3 libdbus-1-dev

script: 
- make clean
- make
- ls -la
- sudo make install
- sudo make systemd_install
- sudo make systemd_uninstall
- sudo make uninstall

notifications:
  email:
    - ruben2020-git@users.sourceforge.net
  on_success: change
  on_failure: always

